sudo: required
services:
- docker
language: java
jdk: oraclejdk8
dist: trusty
env:
  secure: ZsrEpvc06rDKkhlaMQGTEuukrC6tLREaAJJE4n8zM7m4FBB9U2UoY+j/+XIKc4yjKxMlnYJ6MmMRwDria330wAweNd15gEMMo5AEaZvl5imkZRw7wlPeCBwDZ40mc43rxVV5BOV9ooxFSLbRPznwaFzusNZndcAoCpWmPuH2Hh3tvj70zB9fWL3NzynnWQqd4Dnbf3g0AYoaGpq3sdDQRsb/cbiS12i9n2iTAc/bcGxesYthw8vab5zPVDIP9lN6akFNTsWyoq51m1qeXZHwTT4KblRHLzRsZBTVeBYX+dwFzyOWOlWmVVDahUP0LmCWxcduQYZLsdCP7Q5ekoQYMaQMOU/8p9TN9NV5bnxfcJNE9jhqEdO2ThkCCPOWugtn/siTHyP+sysYk5f4/ifD7GgqrHMU2oZ17ht84R7GBIKlTmHxlTBCPIjSzxO8aOFhF0aBxt+aNwayRArWm5jOuVWD4ADSO8xr9p8ZWVLgLQPILdXON5p0Mfst6+F5aOZmtAoCw39+Fqg1AM9DC+A8Y8Ru4fwV6M1x7p8ARXzBDZxZnrJserjUYMia1bT+dxLBdPBw5g2ghbyZ96/Of+qkVrVbonQNQO4HJigmrhfrBObLRzbP4Su+wCxiYG7Z1IUMRlAuATYUbFWaCy/KMOIESLeyQUyV4EpFoloxo/7pdns=
after_success:
- bash <(curl -s https://codecov.io/bash)
- docker login -u amnonxx -p 9ATsrpNEFstn\$J9
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- export CONFIG=amnonxx/piggymetrics-config
- docker build -t $CONFIG:$COMMIT ./config
- docker tag $CONFIG:$COMMIT $CONFIG:$TAG
- docker push $CONFIG:$COMMIT
- export REGISTRY=amnonxx/piggymetrics-registry
- docker build -t $REGISTRY:$COMMIT ./registry
- docker tag $REGISTRY:$COMMIT $REGISTRY:$TAG
- docker push $REGISTRY
- export GATEWAY=amnonxx/piggymetrics-gateway
- docker build -t $GATEWAY:$COMMIT ./gateway
- docker tag $GATEWAY:$COMMIT $GATEWAY:$TAG
- docker push $GATEWAY
- export AUTH_SERVICE=amnonxx/piggymetrics-auth-service
- docker build -t $AUTH_SERVICE:$COMMIT ./auth-service
- docker tag $AUTH_SERVICE:$COMMIT $AUTH_SERVICE:$TAG
- docker push $AUTH_SERVICE
- export ACCOUNT_SERVICE=amnonxx/piggymetrics-account-service
- docker build -t $ACCOUNT_SERVICE:$COMMIT ./account-service
- docker tag $ACCOUNT_SERVICE:$COMMIT $ACCOUNT_SERVICE:$TAG
- docker push $ACCOUNT_SERVICE
- export STATISTICS_SERVICE=amnonxx/piggymetrics-statistics-service
- docker build -t $STATISTICS_SERVICE:$COMMIT ./statistics-service
- docker tag $STATISTICS_SERVICE:$COMMIT $STATISTICS_SERVICE:$TAG
- docker push $STATISTICS_SERVICE
- export NOTIFICATION_SERVICE=amnonxx/piggymetrics-notification-service
- docker build -t $NOTIFICATION_SERVICE:$COMMIT ./notification-service
- docker tag $NOTIFICATION_SERVICE:$COMMIT $NOTIFICATION_SERVICE:$TAG
- docker push $NOTIFICATION_SERVICE
- export MONITORING=amnonxx/piggymetrics-monitoring
- docker build -t $MONITORING:$COMMIT ./monitoring
- docker tag $MONITORING:$COMMIT $MONITORING:$TAG
- docker push $MONITORING
- export TURBINE=amnonxx/piggymetrics-turbine-stream-service
- docker build -t $TURBINE:$COMMIT ./turbine-stream-service
- docker tag $TURBINE:$COMMIT $TURBINE:$TAG
- docker push $TURBINE
- export MONGO_DB=amnonxx/piggymetrics-mongodb
- docker build -t $MONGO_DB:$COMMIT ./mongodb
- docker tag $MONGO_DB:$COMMIT $MONGO_DB:$TAG
- docker push $MONGO_DB
